apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vf3z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0063-tenant/tkrw-pr712-0075-0063-app/devfile-sample-vf3z@sha256:cc367d8ea321401787e5d5b4d3bb168d50596feb649387651e5cbd9d1c0296c8
        name: my-nodejs
        resources: {}
status: {}
